<<<<<<< HEAD:administration/migrations/0001_initial.py
# Generated by Django 4.0.4 on 2022-05-13 17:52
=======
# Generated by Django 4.0.3 on 2022-05-13 17:46
>>>>>>> e8f8786c426b540210f2315afb28df011038b4f6:proj2/administration/migrations/0001_initial.py

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='user_default_image.png', upload_to='user_pics')),
<<<<<<< HEAD:administration/migrations/0001_initial.py
=======
                ('desc', models.IntegerField(default=0)),
>>>>>>> e8f8786c426b540210f2315afb28df011038b4f6:proj2/administration/migrations/0001_initial.py
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
