# Generated by Django 4.0.4 on 2022-05-13 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=800)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('address', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('N', 'New'), ('LN', 'Like New'), ('U', 'Used')], default='New', max_length=10)),
                ('rate', models.DecimalField(decimal_places=0, default=0, max_digits=3, null=True)),
                ('image', models.ImageField(default='item_default_image.jpg', upload_to='item_pics')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.member')),
            ],
        ),
    ]
