# Generated by Django 4.0.4 on 2022-05-01 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=800)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('address', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=10)),
                ('rate', models.DecimalField(decimal_places=0, max_digits=3)),
                ('image', models.ImageField(default='default_image.png', upload_to='user_pics')),
            ],
        ),
    ]
