# Generated by Django 4.0.4 on 2022-05-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemCatalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='rate',
            field=models.DecimalField(decimal_places=0, max_digits=3, null=True),
        ),
    ]
