# Generated by Django 4.0.4 on 2022-05-14 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemCatalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='item_default_image.jpg', upload_to='item_pics/'),
        ),
    ]
