# Generated by Django 4.0.4 on 2022-05-13 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemCatalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='desc',
        ),
    ]
