# Generated by Django 4.0.4 on 2022-05-04 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemCatalog', '0002_alter_item_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='user_pics'),
        ),
    ]
