# Generated by Django 4.0.4 on 2022-05-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemCatalog', '0002_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Like New', 'Like New'), ('Used', 'Used')], default='New', max_length=10),
        ),
    ]
