# Generated by Django 4.0.4 on 2022-05-16 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_member_is_flagged_alter_member_group_member_warn'),
        ('itemCatalog', '0003_alter_item_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flagger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.member')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itemCatalog.item')),
            ],
        ),
    ]
