# Generated by Django 4.0.4 on 2022-05-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_member_is_flagged_alter_member_group_member_warn'),
        ('itemCatalog', '0004_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='likes',
            field=models.ManyToManyField(related_name='items', to='administration.member'),
        ),
    ]
