# Generated by Django 4.0.4 on 2022-05-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemCatalog', '0005_item_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='likes',
        ),
        migrations.AddField(
            model_name='item',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
    ]
