# Generated by Django 4.0.4 on 2022-05-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemCatalog', '0006_alter_item_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('N', 'New'), ('LN', 'Like New'), ('U', 'Used')], default='New', max_length=10),
        ),
    ]
