# Generated by Django 4.0.4 on 2022-05-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('recipient', models.CharField(max_length=100)),
                ('msg_text', models.CharField(help_text='Enter your message', max_length=200)),
                ('send_date', models.DateTimeField(verbose_name='Sent on')),
                ('unread', models.BooleanField(default=False)),
            ],
        ),
    ]
