# Generated by Django 4.0.4 on 2022-05-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='avatar',
            field=models.ImageField(default='user_default_image.jpg', upload_to='user_pics'),
        ),
    ]
