# Generated by Django 4.0.3 on 2022-05-13 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='desc',
        ),
    ]
