# Generated by Django 4.0.4 on 2022-05-05 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='administration.team'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Member_Team',
        ),
    ]
