# Generated by Django 4.0.4 on 2022-05-05 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_member_team_delete_member_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='team',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
