# Generated by Django 4.0.4 on 2022-05-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_member_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='avatar',
            field=models.ImageField(default='default_image.jpg', upload_to='item_pics'),
        ),
    ]
