# Generated by Django 4.0.4 on 2022-05-12 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_alter_member_avatar'),
        ('administration', '0005_alter_member_avatar'),
    ]

    operations = [
    ]
