# Generated by Django 4.0.4 on 2022-05-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_merge_20220512_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='avatar',
            field=models.ImageField(default='user_default_image.jpg', upload_to='item_pics'),
        ),
    ]
