# Generated by Django 4.0.4 on 2022-05-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_alter_member_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='avatar',
            field=models.ImageField(default='user_default_image.png', upload_to='item_pics'),
        ),
    ]
