# Generated by Django 4.0.4 on 2022-05-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_alter_member_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='avatar',
            field=models.ImageField(default='user_default_image.png', upload_to='media/user_pics'),
        ),
    ]
