# Generated by Django 4.0.4 on 2022-05-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0012_alter_member_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='avatar',
            field=models.ImageField(default='static/images/user_default_image.png', upload_to='user_pics'),
        ),
    ]
