# Generated by Django 4.0.4 on 2022-05-15 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0014_alter_member_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member_Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_flagged', models.BooleanField()),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administration.member')),
            ],
        ),
    ]
