# Generated by Django 4.0.4 on 2022-05-15 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0016_member_is_flagged_member_warn'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member_Flag',
        ),
    ]
