# Generated by Django 4.0.4 on 2022-05-15 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('administration', '0017_delete_member_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='group',
            field=models.ForeignKey(choices=[(1, 'Members'), (2, 'User Admin'), (3, 'Item Admin'), (4, 'Super User')], on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
