# Generated by Django 4.0.4 on 2022-05-16 19:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_remove_member_desc_member_is_flagged_and_more'),
        ('itemCatalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='rate',
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='item_default_image.jpg', upload_to='item_pics/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Like New', 'Like New'), ('Used', 'Used')], default='New', max_length=10),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('comment', models.TextField(default='', max_length=250)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.member')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itemCatalog.item')),
            ],
        ),
    ]
